#!/usr/bin/env python
# coding: utf-8

import sys
import os
import argparse
import shutil
import joblib
import pandas as pd
import numpy as np
from pathlib import Path

# --- HEADLESS PLOTTING FIX ---
import matplotlib as mpl
mpl.use('Agg')
mpl.rcParams['figure.max_open_warning'] = 100
import matplotlib.pyplot as plt

# --- IMPORTS (Will only succeed inside snpmanifold_env) ---
try:
    import torch
    import SNPmanifold
    from SNPmanifold.utils_tools import (
        summary_filtering, summary_training, summary_clustering, summary_phylogeny
    )
except ImportError as e:
    # Check if this script is being imported or run
    # If run as main (via subprocess), this error is fatal.
    if __name__ == "__main__":
        print("FATAL ERROR: Could not import SNPmanifold or Torch.")
        print("Ensure this script is running via the 'snpmanifold_env' python executable.")
        print(f"Details: {e}")
        sys.exit(1)
    else:
        # If imported by main script just to check existence, we pass
        pass

# Hardcoded relative paths for module locations (matching dispatcher)
MODULE_RESULTS_DIR = Path("results")
MODULE_PLOTS_DIR = Path("plots")

def save_all_figures_after_call(func, base_name, output_dir, *args, **kwargs):
    """Captures new figures generated by SNPmanifold functions."""
    initial_fignums = set(plt.get_fignums())
    try:
        func(*args, **kwargs)
    except Exception as e:
        print(f"  ERROR: Plotting function '{base_name}' failed with: {e}")
        return

    final_fignums = set(plt.get_fignums())
    new_fignums = sorted(list(final_fignums - initial_fignums))

    if not new_fignums:
        print(f"  Warning: No new figures were detected for '{base_name}'.")
        return

    for i, fig_num in enumerate(new_fignums):
        fig = plt.figure(fig_num)
        plot_name = f"{base_name}_{i+1}.png"
        file_path = os.path.join(output_dir, plot_name)
        fig.savefig(file_path, dpi=300)
        plt.close(fig)
        print(f"  - Saved plot {i+1} to {file_path}")

def run_manifold(args):
    print(f"\n--- [Worker] Starting Manifold Analysis in {os.environ.get('CONDA_DEFAULT_ENV', 'Unknown Env')} ---")

    scratch_output_dir = Path(args.output_dir)
    input_base_dir = MODULE_RESULTS_DIR / args.project

    # Inputs
    base_prefix = f"{args.sample}.{args.cell_type}.cellSNP"
    file_ad = input_base_dir / f"{base_prefix}.tag.AD.mtx.gz"
    file_dp = input_base_dir / f"{base_prefix}.tag.DP.mtx.gz"
    file_vcf = input_base_dir / f"{base_prefix}.base.vcf.gz"
    file_samples = input_base_dir / f"{base_prefix}.samples.tsv.gz"

    for f in [file_ad, file_dp, file_vcf, file_samples]:
        if not f.exists():
            print(f"Error: Missing input file: {f}")
            sys.exit(1)

    # GPU Check
    if torch.cuda.is_available():
        torch.set_default_device('cuda')
        try:
            torch.cuda.set_device('cuda:0')
            print("[Worker] Using GPU: cuda:0")
        except Exception:
            pass
    else:
        print("[Worker] CUDA not available, using CPU.")

    # 1. Initialize
    print("[Worker] Initializing SNP_VAE...")
    snp_model = SNPmanifold.SNP_VAE(
        AD=str(file_ad), DP=str(file_dp), VCF=str(file_vcf),
        SNPread="unnormalized", missing_value="neighbour", UMI_correction=None
    )

    # 2. Filter (set to 0 as per requirements) - Non-interactive fix included
    snp_model.filtering(cell_SNPread_threshold = 0, SNP_DPmean_threshold = 0, SNP_logit_var_threshold = 0)

    # 3. Train
    print("[Worker] Training...")
    snp_model.training(is_cuda=False)

    # 4. Cluster
    print(f"[Worker] Clustering (max_cluster={args.max_cluster})...")
    snp_model.clustering(algorithm="kmeans_umap3d", max_cluster=args.max_cluster)

    # 5. Phylogeny
    print("[Worker] Inferring Phylogeny...")
    snp_model.phylogeny(args.max_cluster)

    # Save Object
    joblib.dump(snp_model, scratch_output_dir / f"{args.sample}_analyzed_object.joblib")

    # Save Clusters TSV
    cell_barcodes = pd.read_csv(file_samples, delimiter='\t', header=None)
    cell_barcodes.columns = ['cell_id']
    cell_barcodes.index = cell_barcodes["cell_id"]
    assigned_label = np.repeat(np.nan, cell_barcodes.shape[0])
    assigned_label[snp_model.cell_filter] = snp_model.assigned_label
    cell_barcodes['clone_id'] = assigned_label

    cell_barcodes.to_csv(scratch_output_dir / "clusters.tsv.gz", sep="\t", index=False, compression="gzip")

    # Plots
    print("[Worker] Saving Plots...")
    plt.close('all')
    save_all_figures_after_call(summary_filtering, "filtering_summary", str(scratch_output_dir), snp_model, dpi=300)
    save_all_figures_after_call(summary_training, "training_summary", str(scratch_output_dir), snp_model, dpi=300)
    save_all_figures_after_call(summary_clustering, "clustering_summary", str(scratch_output_dir), snp_model, dpi=300)
    save_all_figures_after_call(summary_phylogeny, "phylogeny_summary", str(scratch_output_dir), snp_model, SNP_no=50, dpi=300, bad_color="blue", fontsize_c=None, fontsize_x=None, fontsize_y=None, cmap_heatmap=mpl.colormaps['rocket'], SNP_ranking='AF_diff', tree_fig_size=(12, 10))

    # Promote Files (if --final)
    if args.final:
        promote_files(args, scratch_output_dir)

def promote_files(args, scratch_output_dir):
    print("[Worker] Promoting files...")
    res_dest = MODULE_RESULTS_DIR / args.project
    plot_dest = MODULE_PLOTS_DIR / args.project
    if not res_dest.exists(): os.makedirs(res_dest)
    if not plot_dest.exists(): os.makedirs(plot_dest)

    # Logic to fetch initial vs final plots
    initial_dir = Path(args.scratch_dir) / "snpmanifold" / args.project / args.sample / "initial"

    # 1. Clusters Plot
    src_cluster = initial_dir / "clustering_summary_3.png"
    if not src_cluster.exists(): src_cluster = scratch_output_dir / "clustering_summary_3.png"
    if src_cluster.exists(): shutil.copy(src_cluster, plot_dest / f"{args.sample}.{args.cell_type}.clusters.manifold.png")

    # 2. Scatter Plots
    src_2d = scratch_output_dir / "phylogeny_summary_1.png"
    if src_2d.exists(): shutil.copy(src_2d, plot_dest / f"{args.sample}.{args.cell_type}.scatter.2d.manifold.png")

    src_3d = scratch_output_dir / "phylogeny_summary_6.png"
    if src_3d.exists(): shutil.copy(src_3d, plot_dest / f"{args.sample}.{args.cell_type}.scatter.3d.manifold.png")

    # 3. TSV
    src_tsv = scratch_output_dir / "clusters.tsv.gz"
    if src_tsv.exists(): shutil.copy(src_tsv, res_dest / f"{args.sample}.{args.cell_type}.clones.manifold.tsv.gz")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True)
    parser.add_argument("--sample", required=True)
    parser.add_argument("--cell_type", required=True)
    parser.add_argument("--max_cluster", type=int, required=True)
    parser.add_argument("--scratch_dir", required=True)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--final", action="store_true")

    args = parser.parse_args()
    run_manifold(args)
